name: VS17-CLANG-CI

on: [push, pull_request]

jobs:
  ci:
    name: windows-vs17-clang
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: cmake -G "Visual Studio 17 2022" -A x64 -T ClangCL -B build
    - name: Build
      run: cmake --build build --config Release --verbose
    - name: Test
      run: ctest --test-dir build -C Release --output-on-failure
